import type { ImageSource } from 'expo-image';
export const assets: Record<string, ImageSource> = {
  homeJourney: require('../../../assets/catalogue/home-journey.webp'),
  rickshaw: require('../../../assets/catalogue/rickshaw.webp'),
  flowers: require('../../../assets/catalogue/flowers.webp'),
  havan: require('../../../assets/catalogue/havan.webp'),
  leaves: require('../../../assets/catalogue/leaves.webp'),
  prasad: require('../../../assets/catalogue/prasad.webp'),
  idols: require('../../../assets/catalogue/idols.webp'),
  frames: require('../../../assets/catalogue/frames.webp'),
  yantras: require('../../../assets/catalogue/yantras.webp'),
  decor: require('../../../assets/catalogue/decor.webp'),
  books: require('../../../assets/catalogue/books.webp'),
  mantras: require('../../../assets/catalogue/mantras.webp'),
  calendars: require('../../../assets/catalogue/calendars.webp'),
  pages: require('../../../assets/catalogue/pages.webp'),
  fabrics: require('../../../assets/catalogue/fabrics.webp'),
  vastra: require('../../../assets/catalogue/vastra.webp'),
  ornaments: require('../../../assets/catalogue/ornaments.webp'),
  altar: require('../../../assets/catalogue/altar.webp'),
  hero: require('../../../assets/catalogue/hero.webp'),
  otp: require('../../../assets/catalogue/otp.webp'),
  journey: require('../../../assets/catalogue/journey.webp'),
};
